name: Upload Checkpoint to S3

on:
  push:
    paths:
      - 'checkpoints/pixel_cyclegan/latest_net_G_A.pth'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get short SHA
        uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # or your preferred region

      - name: Upload to S3
        run: |
          aws s3 cp checkpoints/pixel_cyclegan/latest_net_G_A.pth s3://deeppixel-dz8ikp/checkpoints/latest_net_G_A_latest.pth
          aws s3 cp checkpoints/pixel_cyclegan/latest_net_G_A.pth s3://deeppixel-dz8ikp/checkpoints/latest_net_G_A_${{ steps.short-sha.outputs.sha }}.pth
